// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKc-r-AZu3FJkcmg6RggRxrXeERZZQeTw',
    appId: '1:923303729323:web:9ff8dcbf7819dea695bfee',
    messagingSenderId: '923303729323',
    projectId: 'shaddi',
    authDomain: 'shaddi.firebaseapp.com',
    storageBucket: 'shaddi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZl1HmS7DlsSaKmuPmGCOdOGNjeNwFEgQ',
    appId: '1:923303729323:android:52cb2fcc39dfdd0995bfee',
    messagingSenderId: '923303729323',
    projectId: 'shaddi',
    storageBucket: 'shaddi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZvbO22FPy2xPqO1Kb_nRtSS9ZzxRj53U',
    appId: '1:923303729323:ios:6e27392660ddac6895bfee',
    messagingSenderId: '923303729323',
    projectId: 'shaddi',
    storageBucket: 'shaddi.firebasestorage.app',
    iosClientId: '923303729323-74sc6ods632enjn2gq857mnhebl0tph7.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZvbO22FPy2xPqO1Kb_nRtSS9ZzxRj53U',
    appId: '1:923303729323:ios:6e27392660ddac6895bfee',
    messagingSenderId: '923303729323',
    projectId: 'shaddi',
    storageBucket: 'shaddi.firebasestorage.app',
    iosClientId: '923303729323-74sc6ods632enjn2gq857mnhebl0tph7.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaadi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKc-r-AZu3FJkcmg6RggRxrXeERZZQeTw',
    appId: '1:923303729323:web:f39d97c011bcb25095bfee',
    messagingSenderId: '923303729323',
    projectId: 'shaddi',
    authDomain: 'shaddi.firebaseapp.com',
    storageBucket: 'shaddi.firebasestorage.app',
  );
}
